spring:
  datasource:
    url: jdbc:mysql://127.0.1:3306/doctor?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 8FQ5kCqyg1-Y
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

